version: "3.8"

services:
  auth:
    container_name: fafago-auth
    image: 'fafagoauth/auth:testdb'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "8080:80"
    networks:
      - auth-network
    mem_limit: 500m
    restart: 'unless-stopped'
  auth_mongo:
    container_name: fafago-auth-mongo
    image: 'mongo'
    restart: "unless-stopped"
    ports:
      - "27018:27017"
    networks:
      - auth-network
    volumes:
      - 'auth_mongo_volume:/data/db'
    mem_limit: 1000m
    restart: 'unless-stopped'
  auth_redis:
    container_name: fafago-auth-redis
    image: 'redis'
    networks:
      - auth-network
    mem_limit: 1000m
    restart: "unless-stopped"
networks:
  auth-network:
    driver: bridge

volumes:
  auth_mongo_volume: null
networks:
  auth-network:
    external: false