apiVersion: v1
kind: Secret
metadata:
  name: seedautentication-auth-$BRANCH_NAME
  namespace: app
type: Opaque
data:
  SEED_AUTENTICATION: bWVnYXVsdHJhcmFuZG9tc2VlZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-$BRANCH_NAME
  namespace: app
  labels:
    app: auth-$BRANCH_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-$BRANCH_NAME
  template:
    metadata:
      labels:
        app: auth-$BRANCH_NAME
    spec:
      containers:
      - name: auth
        image: $DOCKER_IMAGES
        ports:
        - containerPort: 80
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "80"
          - name: MONGO_HOSTNAME
            value: localhost
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: fafago_user_db
          - name: SEED_AUTENTICATION
            valueFrom:
              secretKeyRef:
                name: seedautentication-auth-$BRANCH_NAME
                key: SEED_AUTENTICATION
          - name: REDIS_HOSTNAME
            value: localhost
          - name: REDIS_PORT
            value: "6379"
          - name: PRODUCTS_HOSTNAME
            value: http://10.0.5.146:8080
          - name: REVIEWS_HOSTNAME
            value: http://10.0.0.157:80
      - name: redis
        image: redis:6.0.9-alpine
        ports:
        - containerPort: 6379
      - name: mongo
        image: mongo:4.4.3-bionic
        ports:
        - containerPort: 27017
