version: "3.8"

services:
  auth:
    container_name: fafago-auth
    image: 'fafagoauth/auth:test'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - PRODUCTS_HOSTNAME=${PRODUCTS_HOSTNAME}
      - REVIEWS_HOSTNAME${REVIEWS_HOSTNAME}      
      - CLOUDINARY_CLOUD_NAME=
      - CLOUDINARY_NAME=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
    ports:
      - "80:80"
    networks:
      - auth_network
    mem_limit: 500m
    restart: 'unless-stopped'
  auth_mongo:
    container_name: fafago-auth-mongo
    image: 'mongo'
#    ports:
#      - "27017:27017"
    networks:
      auth_network:
        aliases:
          - ${MONGO_HOSTNAME}
    volumes:
      - 'auth_mongo_volume:/data/db'
    mem_limit: 1000m
    restart: 'unless-stopped'
  auth_redis:
    container_name: fafago-auth-redis
    image: 'redis'
#    ports:
#      - "6379:6379"
    networks:
      auth_network:
        aliases:
          - ${REDIS_HOSTNAME}
    mem_limit: 1000m
    restart: "unless-stopped"

networks:
  auth_network: null

volumes:
  auth_mongo_volume: null